- name: Install zsh
  community.general.pacman:
    name: zsh
    state: present
    update_cache: yes

- name: Ensure user shell is zsh
  user: { name: "{{ primary_user }}", shell: "{{ primary_shell }}" }

- block:
    - name: Install oh-my-zsh (non-interactive)
      shell: |
        export RUNZSH=no CHSH=no KEEP_ZSHRC=yes
        if [ ! -d "$HOME/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi

    - name: Ensure ~/.zshrc exists
      file: { path: "{{ user_home }}/.zshrc", state: touch }

    - name: Append aliases/pywal snippet
      blockinfile:
        path: "{{ user_home }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED zshrc APPEND"
        block: "{{ lookup('file', role_path + '/files/zshrc.append') }}"
  become: false
  become_user: "{{ primary_user }}"
  vars:
    user_home: "/home/{{ primary_user }}"

- name: Enable systemd user ssh-agent
  become: false
  become_user: "{{ primary_user }}"
  systemd:
    name: ssh-agent.service
    scope: user
    enabled: true
    state: started
