- name: Ensure ~/.ssh exists
  file:
    path: "/home/{{ primary_user }}/.ssh"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0700'

- name: Set key paths
  set_fact:
    _github_key: "{{ github_key_path | default('/home/' ~ primary_user ~ '/.ssh/woody') }}"
    _serverus_key: "{{ serverus_key_path | default('/home/' ~ primary_user ~ '/.ssh/serverus') }}"

- name: Install GitHub private key (vault)
  copy:
    dest: "{{ _github_key }}"
    content: "{{ vault_github_private_key }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0600'

- name: Install server private key (vault)
  copy:
    dest: "{{ _serverus_key }}"
    content: "{{ vault_serverus_private_key }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0600'

# ---- SSH config so aliases are unnecessary (use `ssh serverus`) ----
# Also auto-load keys into the running agent on first use.
- name: Install ~/.ssh/config
  copy:
    dest: "/home/{{ primary_user }}/.ssh/config"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: '0600'
    content: |
      Host github.com
        HostName github.com
        User git
        IdentityFile {{ _github_key }}
        IdentitiesOnly yes
        AddKeysToAgent yes

      Host serverus
        HostName {{ serverus_host | default('192.168.0.12') }}
        Port {{ serverus_port | default(2221) }}
        User {{ primary_user }}
        IdentityFile {{ _serverus_key }}
        IdentitiesOnly yes
        AddKeysToAgent yes

# ---- Known hosts (avoid interactive fingerprint prompts) ----
- name: Add GitHub to known_hosts
  known_hosts:
    path: "/home/{{ primary_user }}/.ssh/known_hosts"
    name: "github.com"
    key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com 2>/dev/null') }}"
    state: present
  become: false
  become_user: "{{ primary_user }}"

- name: Add serverus to known_hosts
  known_hosts:
    path: "/home/{{ primary_user }}/.ssh/known_hosts"
    name: "{{ serverus_host | default('192.168.0.12') }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -p ' ~ (serverus_port | default(2221) | string) ~ ' -t ed25519 ' ~ (serverus_host | default('192.168.0.12')) ~ ' 2>/dev/null') }}"
    state: present
  become: false
  become_user: "{{ primary_user }}"