# Repo packages first
- name: Repo apps (firefox, alacritty, neovim, pywal)
  community.general.pacman:
    name:
      - firefox
      - alacritty
      - neovim
      - python-pywal
    state: present
    update_cache: yes

- block:
    - name: Install yay (AUR helper)
      kewlfft.aur.aur:
        name: yay
        state: present

    - name: Install AUR apps (spotify, VS Code, Joplin)
      kewlfft.aur.aur:
        name:
          - spotify
          - visual-studio-code-bin
          - joplin
        state: present
  become: false
  become_user: "{{ primary_user }}"