- name: Enable parallel downloads
  lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?ParallelDownloads'
    line: 'ParallelDownloads = 5'

- name: Update + upgrade
  pacman: { update_cache: yes, upgrade: yes }

- name: Base packages
  community.general.pacman:
    name:
      - base-devel
      - git
      - wget
      - curl
      - unzip
      - zip
      - openssh
      - networkmanager
      - sudo
      - python
      - which
    state: present

- name: Enable NetworkManager + sshd
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: [NetworkManager, sshd]

- name: Ensure base-devel installed
  community.general.pacman:
    name: base-devel
    state: present

- name: Allow pacman without password for AUR installs
  copy:
    dest: /etc/sudoers.d/10-aur-pacman
    owner: root
    group: root
    mode: '0440'
    content: "{{ primary_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman\n"
    validate: 'visudo -cf %s'